/* bin2c: convert a binary file into a C array.
 *   bin2c INPUT OUTPUT SYMBOL
 * emits:
 *   const unsigned char SYMBOL[] = { ... };
 *   const unsigned long SYMBOL_len = N;
 */
#include <stdio.h>
#include <stdlib.h>

int
main(int argc, char **argv)
{
    FILE *in, *out;
    unsigned long n = 0;
    int c, col = 0;

    if (argc != 4) {
        fprintf(stderr, "usage: bin2c INPUT OUTPUT SYMBOL\n");
        return EXIT_FAILURE;
    }
    in = fopen(argv[1], "rb");
    if (!in) {
        fprintf(stderr, "bin2c: cannot open %s\n", argv[1]);
        return EXIT_FAILURE;
    }
    out = fopen(argv[2], "w");
    if (!out) {
        fprintf(stderr, "bin2c: cannot create %s\n", argv[2]);
        return EXIT_FAILURE;
    }
    fprintf(out, "/* generated by bin2c from %s */\n", argv[1]);
    fprintf(out, "const unsigned char %s[] = {\n", argv[3]);
    while ((c = getc(in)) != EOF) {
        fprintf(out, "%d,", c);
        n++;
        if (++col == 20) {
            putc('\n', out);
            col = 0;
        }
    }
    /* trailing NUL sentinel (not counted in _len) so text-parsing
       consumers like the DLBMEM archive reader can treat the data as
       a bounded C string */
    fprintf(out, "0\n};\nconst unsigned long %s_len = %luUL;\n", argv[3], n);
    if (ferror(in) || fclose(out) || fclose(in)) {
        fprintf(stderr, "bin2c: I/O error\n");
        remove(argv[2]);
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}
