/* hex2c: convert a BDF-style .hex bitmap font into a C glyph table.
 *   hex2c INPUT OUTPUT SYMBOL
 *
 * Input lines look like "0041:0018242442427E424242420000000000" --
 * codepoint, colon, hex-encoded bitmap rows.  For an 8x8 font each
 * narrow glyph is 8 bytes (16 hex digits); double-width glyphs are 16
 * bytes and are skipped.  Codepoints >= CP_LIMIT are skipped to keep
 * the table small (the game only draws BMP symbols well below it).
 *
 * emits:
 *   const struct SYMBOL_glyph { unsigned int cp; unsigned char rows[8]; };
 *   const struct SYMBOL_glyph SYMBOL[] = { ... };   (sorted by cp)
 *   const int SYMBOL_count = N;
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CP_LIMIT 0x3000
#define MAXGLYPHS 8192

struct glyph {
    unsigned int cp;
    unsigned char rows[8];
};

static int
cmp_glyph(const void *a, const void *b)
{
    unsigned int ca = ((const struct glyph *) a)->cp;
    unsigned int cb = ((const struct glyph *) b)->cp;

    return (ca > cb) - (ca < cb);
}

int
main(int argc, char **argv)
{
    static struct glyph g[MAXGLYPHS];
    char line[256];
    FILE *in, *out;
    int i, n = 0, lineno = 0;

    if (argc != 4) {
        fprintf(stderr, "usage: hex2c INPUT OUTPUT SYMBOL\n");
        return EXIT_FAILURE;
    }
    in = fopen(argv[1], "r");
    if (!in) {
        fprintf(stderr, "hex2c: cannot open %s\n", argv[1]);
        return EXIT_FAILURE;
    }
    while (fgets(line, sizeof line, in)) {
        unsigned int cp;
        const char *colon = strchr(line, ':');
        size_t digits;

        lineno++;
        if (!colon || sscanf(line, "%x", &cp) != 1)
            continue;
        digits = strspn(colon + 1, "0123456789abcdefABCDEF");
        if (digits != 16) /* narrow 8x8 only; skip double-width */
            continue;
        if (cp >= CP_LIMIT && cp != 0xfffd) /* keep replacement char */
            continue;
        if (n == MAXGLYPHS) {
            fprintf(stderr, "hex2c: too many glyphs (line %d)\n", lineno);
            return EXIT_FAILURE;
        }
        g[n].cp = cp;
        for (i = 0; i < 8; i++) {
            unsigned int byte;

            if (sscanf(colon + 1 + 2 * i, "%2x", &byte) != 1)
                break;
            g[n].rows[i] = (unsigned char) byte;
        }
        if (i == 8)
            n++;
    }
    fclose(in);
    if (!n) {
        fprintf(stderr, "hex2c: no usable glyphs in %s\n", argv[1]);
        return EXIT_FAILURE;
    }
    qsort(g, n, sizeof *g, cmp_glyph);

    out = fopen(argv[2], "w");
    if (!out) {
        fprintf(stderr, "hex2c: cannot create %s\n", argv[2]);
        return EXIT_FAILURE;
    }
    fprintf(out, "/* generated by hex2c from %s */\n", argv[1]);
    fprintf(out, "struct %s_glyph { unsigned int cp; unsigned char rows[8]; };\n",
            argv[3]);
    fprintf(out, "const struct %s_glyph %s[] = {\n", argv[3], argv[3]);
    for (i = 0; i < n; i++)
        fprintf(out, "{%u,{%u,%u,%u,%u,%u,%u,%u,%u}},\n", g[i].cp,
                g[i].rows[0], g[i].rows[1], g[i].rows[2], g[i].rows[3],
                g[i].rows[4], g[i].rows[5], g[i].rows[6], g[i].rows[7]);
    fprintf(out, "};\nconst int %s_count = %d;\n", argv[3], n);
    if (fclose(out)) {
        fprintf(stderr, "hex2c: I/O error writing %s\n", argv[2]);
        remove(argv[2]);
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}
