/* PDCursesMod platform backend for SDL3 -- NetHack SDL3 fork, 2026.
 * Modeled on PDCursesMod's sdl2 backend (public domain), rendering
 * from an embedded 8x8 bitmap font at an integer scale instead of a
 * font surface / TTF. */

#ifndef PDCSDL3_H
#define PDCSDL3_H

#include <SDL3/SDL.h>

#include <curspriv.h>

extern SDL_Window *pdc_window;
extern SDL_Surface *pdc_screen; /* window surface, pixel units */
extern int pdc_sheight, pdc_swidth; /* drawable size in pixels */
extern int pdc_fheight, pdc_fwidth; /* cell size in pixels */
extern int pdc_fthick;              /* highlight line thickness */
extern int pdc_scale;               /* font pixel multiplier */

/* called on the first window-close request (wired to NetHack's
   hangup handling by sys/sdl3/sdl3main.c); a second request exits */
extern void (*pdc_sdl3_quit_hook)(void);

void PDC_update_rects(void);
void PDC_pump_and_peep(void);
void PDC_refresh_pixel_geometry(void);
void PDC_check_for_blinking(void);

/* embedded font (generated by hex2c from unscii-8) */
struct nh_font8_glyph {
    unsigned int cp;
    unsigned char rows[8];
};
extern const struct nh_font8_glyph nh_font8[];
extern const int nh_font8_count;

#endif /* PDCSDL3_H */
