# pack_dlb.cmake: assemble the nhdat archive in the staged dat directory.
#
#   cmake -DSRCDAT=<repo>/dat -DSTAGEDAT=<build>/stage/dat
#         -DDLB_EXE=<path to dlb tool> -P pack_dlb.cmake
#
# The makedefs outputs (data rumors oracles engrave epitaph bogusmon) must
# already exist in STAGEDAT; this script adds the static members from the
# source dat/ directory, writes dlb.lst, and runs dlb.

foreach(var SRCDAT STAGEDAT DLB_EXE)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "pack_dlb.cmake: ${var} not set")
    endif()
endforeach()

# Fixed members shipped verbatim (help texts + license + tribute);
# normally passed in via -DFIXED from CMakeLists.txt so the member
# list and the build dependencies stay in sync.
if(DEFINED FIXED)
    set(fixed ${FIXED})
else()
    set(fixed
        help hh cmdhelp keyhelp history opthelp optmenu usagehlp wizhelp
        luahelper license tribute)
endif()

# All level/dungeon/quest/library Lua files.
file(GLOB lua_paths "${SRCDAT}/*.lua")

# Generated by makedefs into STAGEDAT beforehand.
set(generated data rumors oracles engrave epitaph bogusmon)

set(members)
foreach(f IN LISTS fixed)
    file(COPY_FILE "${SRCDAT}/${f}" "${STAGEDAT}/${f}" ONLY_IF_DIFFERENT)
    list(APPEND members "${f}")
endforeach()
foreach(p IN LISTS lua_paths)
    get_filename_component(f "${p}" NAME)
    file(COPY_FILE "${p}" "${STAGEDAT}/${f}" ONLY_IF_DIFFERENT)
    list(APPEND members "${f}")
endforeach()
foreach(f IN LISTS generated)
    if(NOT EXISTS "${STAGEDAT}/${f}")
        message(FATAL_ERROR "pack_dlb.cmake: missing makedefs output ${f}")
    endif()
    list(APPEND members "${f}")
endforeach()

list(JOIN members "\n" lst)
file(WRITE "${STAGEDAT}/dlb.lst" "${lst}\n")

file(REMOVE "${STAGEDAT}/nhdat")
execute_process(
    COMMAND "${DLB_EXE}" cIf dlb.lst nhdat
    WORKING_DIRECTORY "${STAGEDAT}"
    RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "dlb failed with status ${rc}")
endif()

list(LENGTH members n)
message(STATUS "packed nhdat with ${n} members")
