/* NetHack 5.0  sdl3main.c */
/* Copyright (c) NetHack SDL3 fork, 2026. */
/* NetHack may be freely redistributed.  See license for details. */

/* main() for the SDL3 host platform.  Modeled on sys/libnh/libnhmain.c
 * with the prefix handling of sys/windows/windmain.c: no chdir(); every
 * runtime file lives under either the executable's directory (portable
 * mode) or SDL_GetPrefPath(). */

#include "hack.h"
#include "dlb.h"

#include <SDL3/SDL.h>

#ifndef WIN32
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#endif

#include "default_files.h"

/* generated by bin2c from dat/symbols */
extern const unsigned char nh_symbols_blob[];
extern const unsigned long nh_symbols_blob_len;

char nh_basedir[FQN_MAX_FILENAME]; /* executable's directory */
char nh_prefdir[FQN_MAX_FILENAME]; /* SDL_GetPrefPath() */

/* The SDL3 curses backend calls this on the first window-close
 * request; treat it like a hangup so the game saves and exits
 * cleanly (SAFERHANGUP defers it to the command loop).  Defined here
 * rather than in the backend so wincon bring-up builds still link. */
#ifdef HANGUPHANDLING
static void
sdl3_close_request(void)
{
    hangup(1);
}
void (*pdc_sdl3_quit_hook)(void) = sdl3_close_request;
#else
void (*pdc_sdl3_quit_hook)(void) = 0;
#endif

#ifdef WIN32
char portable_device_path[_MAX_PATH]; /* read by src/cfgfiles.c */
boolean portable = FALSE;
#endif

boolean whoami(void);
static void sdl3_init_paths(void);
static void seed_file(int prefix, const char *name, const void *data,
                      unsigned long len);
static void sdl3_seed_files(void);
static void process_options(int, char **);
static void wd_message(void);

int
main(int argc, char *argv[])
{
    NHFILE *nhfp;
    boolean exact_username;
    boolean resuming = FALSE; /* assume new game */
    boolean plsel_once = FALSE;
#ifdef WIN32
    int getlock_result = 0;
#endif

    early_init(argc, argv);

    gh.hname = argv[0];
    svh.hackpid = getpid();
    /* No umask() here, unlike unixmain.c: its 0777 & ~FCMASK strips
     * the execute bits, which is fatal for the directories this port
     * creates at runtime (SDL_GetPrefPath, save/), and its purpose --
     * group-writable files for a shared install -- doesn't apply to a
     * per-user prefdir. */

    choose_windows(DEFAULT_WINDOW_SYS);

    sdl3_init_paths();
    sdl3_seed_files();

    if (argc > 1) {
        if (argcheck(argc, argv, ARG_VERSION) == 2)
            exit(EXIT_SUCCESS);
        if (argcheck(argc, argv, ARG_SHOWPATHS) == 2)
            gd.deferred_showpaths = TRUE; /* handled by initoptions() */
        if (argcheck(argc, argv, ARG_DEBUG) == 1) {
            argc--;
            argv++;
        }
    }

    if (argc > 1 && !strncmp(argv[1], "-s", 2)
        && strncmp(argv[1], "-style", 6)) {
        /* score listing */
        initoptions();
        prscore(argc, argv);
        exit(EXIT_SUCCESS);
    }

    initoptions();
#ifdef PANICTRACE
    ARGV0 = gh.hname; /* save for possible stack trace */
#ifndef NO_SIGNAL
    panictrace_setsignals(TRUE);
#endif
#endif
    exact_username = whoami();

    u.uhp = 1; /* prevent RIP on early quits */
    program_state.preserve_locks = 1;
#ifndef NO_SIGNAL
    sethanguphandler((SIG_RET_TYPE) hangup);
#endif

    process_options(argc, argv); /* command line options */
    init_nhwindows(&argc, argv);

    if (!dlb_init()) {
        raw_printf("dlb_init failure: cannot find game data (nhdat in %s).",
                   gf.fqn_prefix[DATAPREFIX] ? gf.fqn_prefix[DATAPREFIX]
                                             : "?");
        error("dlb_init failure.");
    }

    /* wizard mode access is deferred until here */
    set_playmode(); /* sets plname to "wizard" for wizard mode */
    /* hide any hyphens from plnamesuffix() */
    gp.plnamelen = exact_username ? (int) strlen(svp.plname) : 0;
    /* strip role,race,&c suffix; calls askname() if plname[] is empty
       or holds a generic user name like "player" or "games" */
    plnamesuffix();

    if (wizard) {
#ifndef WIN32 /* Windows always locks by character name */
        /* use character name rather than lock letter for file names */
        gl.locknum = 0;
#endif
    } else {
#ifndef NO_SIGNAL
        /* suppress interrupts while processing lock file */
        (void) signal(SIGQUIT, SIG_IGN);
        (void) signal(SIGINT, SIG_IGN);
#endif
    }

    /*
     * Initialize the vision system.  This must be before mklev() on a
     * new game or before a level restore on a saved game.
     */
    vision_init();

    init_sound_disp_gamewindows();

 attempt_restore:
    if (*svp.plname) {
#ifdef WIN32
        if ((getlock_result = getlock()) == 0)
            nethack_exit(EXIT_SUCCESS);
        if (getlock_result < 0) {
            /* destroyed the old game; nothing else will name the
               savefile for the new one (cf. windmain.c) */
            if (program_state.in_self_recover)
                program_state.in_self_recover = FALSE;
            set_savefile_name(TRUE);
        }
#else
        getlock();
#endif
        program_state.preserve_locks = 0; /* after getlock() */
    }

    if (*svp.plname
#ifdef WIN32
        && getlock_result != -1 /* not "destroy the old game" */
#endif
        && (nhfp = restore_saved_game()) != 0) {
        const char *fq_save = fqname(gs.SAVEF, SAVEPREFIX, 1);

#ifndef WIN32 /* a read-only file can't be deleted/rewritten on Windows */
        (void) chmod(fq_save, 0); /* disallow parallel restores */
#endif
#ifndef NO_SIGNAL
        (void) signal(SIGINT, (SIG_RET_TYPE) done1);
#endif
        pline("Restoring save file...");
        mark_synch(); /* flush output */
        if (dorecover(nhfp)) {
            resuming = TRUE; /* not starting new game */
            if (program_state.in_self_recover)
                program_state.in_self_recover = FALSE; /* see files.c */
            wd_message();
            if (discover || wizard) {
                if (y_n("Do you want to keep the save file?") == 'n') {
                    (void) delete_savefile();
                } else {
#ifndef WIN32
                    (void) chmod(fq_save, FCMASK); /* back to readable */
#endif
                }
            }
        }
    }

    if (!resuming) {
        boolean neednewlock = (!*svp.plname);
        /* new game:  start by choosing role, race, etc;
           player might change the hero's name while doing that,
           in which case we try to restore under the new name
           and skip selection this time if that didn't succeed */
        if (!iflags.renameinprogress || iflags.defer_plname || neednewlock) {
            if (!plsel_once)
                player_selection();
            plsel_once = TRUE;
            if (neednewlock && *svp.plname)
                goto attempt_restore;
            if (iflags.renameinprogress) {
                /* remove the old name's empty level-0 lock; the
                   getlock() at attempt_restore re-derives the lock
                   from the new name (calling it here as well would
                   trip its own game-in-progress prompt) */
                delete_levelfile(0);
                goto attempt_restore;
            }
        }
        newgame();
        wd_message();
    }

    /* moveloop() never returns but isn't flagged NORETURN */
    moveloop(resuming);

    exit(EXIT_SUCCESS);
    /*NOTREACHED*/
    return 0;
}

/* Set every fqn_prefix[] slot from SDL3's path functions.  Both
 * SDL_GetBasePath() and SDL_GetPrefPath() return strings with a
 * trailing path separator, which is exactly fqname()'s contract,
 * and SDL_GetPrefPath() creates the directory. */
static void
sdl3_init_paths(void)
{
    const char *base;
    char *pref;
    int i;

    if (!SDL_Init(0))
        error("SDL_Init failed: %s", SDL_GetError());
    (void) atexit(SDL_Quit);

    base = SDL_GetBasePath();
    if (!base)
        error("SDL_GetBasePath failed: %s", SDL_GetError());
    (void) strncpy(nh_basedir, base, sizeof nh_basedir - 1);

    pref = SDL_GetPrefPath("NetHack", "NetHack-SDL3");
    if (!pref)
        error("SDL_GetPrefPath failed: %s", SDL_GetError());
    (void) strncpy(nh_prefdir, pref, sizeof nh_prefdir - 1);
    SDL_free(pref);

#ifdef NETHACK_SDL3_PORTABLE
    for (i = 0; i < PREFIX_COUNT; i++)
        gf.fqn_prefix[i] = nh_basedir;
#ifdef WIN32
    portable = TRUE;
    (void) strncpy(portable_device_path, nh_basedir,
                   sizeof portable_device_path - 1);
#endif
#else
    for (i = 0; i < PREFIX_COUNT; i++)
        gf.fqn_prefix[i] = nh_prefdir;
    gf.fqn_prefix[DATAPREFIX] = nh_basedir; /* nhdat beside the exe */
#endif

#ifdef WIN32
    for (i = 0; i < PREFIX_COUNT; i++)
        fqn_prefix_locked[i] = TRUE;
#endif
}

/* Write an initial copy of a runtime file if it doesn't exist yet. */
static void
seed_file(int prefix, const char *name, const void *data, unsigned long len)
{
    char path[FQN_MAX_FILENAME];
    FILE *fp;

    if (snprintf(path, sizeof path, "%s%s", gf.fqn_prefix[prefix], name)
        >= (int) sizeof path)
        return;
    fp = fopen(path, "rb");
    if (fp) {
        (void) fclose(fp);
        return; /* already there */
    }
    fp = fopen(path, "wb");
    if (!fp)
        error("Cannot create %s.", path);
    if (len && fwrite(data, 1, len, fp) != len) {
        (void) fclose(fp);
        error("Cannot write %s.", path);
    }
    if (fclose(fp))
        error("Cannot write %s.", path);
}

/* First-run setup: sysconf, run-time config, symbols parsing file, and
 * the files/directories that must pre-exist for locking and scores. */
static void
sdl3_seed_files(void)
{
    seed_file(SYSCONFPREFIX, SYSCF_FILE, sdl3_default_sysconf,
              (unsigned long) strlen(sdl3_default_sysconf));
    seed_file(CONFIGPREFIX, CONFIG_FILE, sdl3_default_nethackrc,
              (unsigned long) strlen(sdl3_default_nethackrc));
    seed_file(SYSCONFPREFIX, SYMBOLS, nh_symbols_blob, nh_symbols_blob_len);
#ifndef WIN32
    {
        char path[FQN_MAX_FILENAME];

        /* set_savefile_name() on UNIX hardcodes a save/ subdirectory */
        if (snprintf(path, sizeof path, "%ssave", gf.fqn_prefix[SAVEPREFIX])
            < (int) sizeof path)
            (void) mkdir(path, 0755);
        /* fcntl locking opens its targets without O_CREAT */
        seed_file(SCOREPREFIX, RECORD, "", 0);
        seed_file(SCOREPREFIX, LOGFILE, "", 0);
        seed_file(SCOREPREFIX, XLOGFILE, "", 0);
        seed_file(LOCKPREFIX, HLOCK, "", 0);
    }
#else
    check_recordfile((char *) 0);
#endif
}

/* caveat: argv elements might be arbitrarily long */
static void
process_options(int argc, char *argv[])
{
    int i, l;

    while (argc > 1 && argv[1][0] == '-') {
        argv++;
        argc--;
        l = (int) strlen(*argv);
        /* must supply at least 4 chars to match "-XXXgraphics" */
        if (l < 4)
            l = 4;

        switch (argv[0][1]) {
        case 'D':
        case 'd':
            if ((argv[0][1] == 'D' && !argv[0][2])
                || !strcmpi(*argv, "-debug")) {
                wizard = TRUE, discover = FALSE;
            } else if (!strncmpi(*argv, "-DECgraphics", l)) {
                load_symset("DECGraphics", PRIMARYSET);
                switch_symbols(TRUE);
            } else {
                raw_printf("Unknown option: %.60s", *argv);
            }
            break;
        case 'X':
            discover = TRUE, wizard = FALSE;
            break;
        case 'u':
            if (argv[0][2]) {
                (void) strncpy(svp.plname, argv[0] + 2,
                               sizeof svp.plname - 1);
                gp.plnamelen = 0;
            } else if (argc > 1) {
                argc--;
                argv++;
                (void) strncpy(svp.plname, argv[0], sizeof svp.plname - 1);
                gp.plnamelen = 0;
            } else {
                raw_print("Player name expected after -u");
            }
            break;
        case 'I':
        case 'i':
            if (!strncmpi(*argv, "-IBMgraphics", l)) {
                load_symset("IBMGraphics", PRIMARYSET);
                load_symset("RogueIBM", ROGUESET);
                switch_symbols(TRUE);
            } else {
                raw_printf("Unknown option: %.60s", *argv);
            }
            break;
        case 'p': /* profession (role) */
            if (argv[0][2]) {
                if ((i = str2role(&argv[0][2])) >= 0)
                    flags.initrole = i;
            } else if (argc > 1) {
                argc--;
                argv++;
                if ((i = str2role(argv[0])) >= 0)
                    flags.initrole = i;
            }
            break;
        case 'r': /* race */
            if (argv[0][2]) {
                if ((i = str2race(&argv[0][2])) >= 0)
                    flags.initrace = i;
            } else if (argc > 1) {
                argc--;
                argv++;
                if ((i = str2race(argv[0])) >= 0)
                    flags.initrace = i;
            }
            break;
        case 'w': /* windowtype */
            config_error_init(FALSE, "command line", FALSE);
            choose_windows(&argv[0][2]);
            config_error_done();
            break;
        case '@':
            flags.randomall = 1;
            break;
        default:
            if ((i = str2role(&argv[0][1])) >= 0) {
                flags.initrole = i;
                break;
            }
        }
    }

#ifndef WIN32 /* gl.locknum only exists for UNIX/VMS */
#ifdef MAX_NR_OF_PLAYERS
    if (!gl.locknum || gl.locknum > MAX_NR_OF_PLAYERS)
        gl.locknum = MAX_NR_OF_PLAYERS;
#endif
#ifdef SYSCF
    if (!gl.locknum || (sysopt.maxplayers && gl.locknum > sysopt.maxplayers))
        gl.locknum = sysopt.maxplayers;
#endif
#endif
}

/* returns True iff we set plname[] to a username containing a hyphen */
boolean
whoami(void)
{
    if (!*svp.plname) {
        const char *s;

        s = nh_getenv("USER");
        if (!s || !*s)
            s = nh_getenv("LOGNAME");
        if (!s || !*s)
            s = nh_getenv("USERNAME"); /* Windows */

        if (s && *s) {
            (void) strncpy(svp.plname, s, sizeof svp.plname - 1);
            if (strchr(svp.plname, '-'))
                return TRUE;
        }
    }
    return FALSE;
}

static void
wd_message(void)
{
    if (iflags.wiz_error_flag) {
        if (sysopt.wizards && sysopt.wizards[0]) {
            char *tmp = build_english_list(sysopt.wizards);
            pline("Only user%s %s may access debug (wizard) mode.",
                  strchr(sysopt.wizards, ' ') ? "s" : "", tmp);
            free(tmp);
        } else {
            You("cannot access debug (wizard) mode.");
        }
        wizard = FALSE; /* (paranoia) */
        if (!iflags.explore_error_flag)
            pline("Entering explore/discovery mode instead.");
    } else if (iflags.explore_error_flag) {
        You("cannot access explore mode.");
        discover = iflags.deferred_X = FALSE; /* (more paranoia) */
    } else if (discover)
        You("are in non-scoring explore/discovery mode.");
}

/*sdl3main.c*/
